name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nicowillis/setup-theos@main
    - run: make package FINALPACKAGE=1
    - uses: actions/upload-artifact@v4
      with:
        name: MicBoard
        path: packages/*.deb
